# set clone depth
clone_depth: 5                  # clone entire repository history if not defined

environment:
  matrix:
    - CYG_ARCH: x86
      CYG_ROOT: C:/cygwin
    - CYG_ARCH: x86_64
      CYG_ROOT: C:/cygwin64

install:
- '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l %CYG_ROOT%/var/cache/setup -P curl'
- SET "PATH=%CYG_ROOT%\bin;%PATH%"

build: off

test_script:
  - '%CYG_ROOT%/bin/bash -lc "g++ --version && cd $APPVEYOR_BUILD_FOLDER && 
cd extern && curl -L -O https://github.com/fmtlib/fmt/archive/5.3.0.tar.gz && tar -xzf 5.3.0.tar.gz && rm -f 5.3.0.tar.gz && cd ..  && ./autogen.sh && ./configure && make check"'
